name: InvadedSoup
version: ${project.version}
main: me.yochran.invadedsoup.InvadedSoup
api-version: 1.16
depend: [WorldGuard, WorldEdit]
authors: [Yochran]
description: A replica of InvadedLand's soup core.
commands:
  soup:
    description: Get all subcommands for the soup core
    usage: /<command>
    aliases: [invadedsoup, soupcore, core]
  Help:
    description: Gets the soup cores help for normal players.
    usage: /<command>
  ToggleDrops:
    description: Toggle off or on item drops.
    usage: /<command>
    aliases: tdp
  Spawn:
    description: Teleport a player to spawn.
    usage: /<command>
  Message:
    description: Message another player on the server privately.
    usage: /<command>
    aliases: [whisper, msg, tell, t, w]
  Reply:
    description: Reply to a player currently messaging you.
    usage: /<command>
    aliases: r
  ToggleMessages:
    description: Toggle on or off private messages.
    usage: /<command>
    aliases: [tpm, blockmsg, blockmessages, togglemsg]
  ToggleGlobalChat:
    description: Toggle on or off global chat.
    usage: /<command>
    aliases: [togglechat, tc, tgc]
  ToggleMessageSounds:
    description: Toggle on or off messaging sounds.
    usage: /<command>
    aliases: [tms, togglesounds, ts]
