name: InvadedSoup
version: ${project.version}
main: me.yochran.invadedsoup.InvadedSoup
api-version: 1.16
depend: [WorldGuard, WorldEdit]
authors: [Yochran]
description: A replica of InvadedLand's soup core.
commands:
  soup:
    description: Get all subcommands for the soup core
    usage: /<command>
    aliases: [invadedsoup, soupcore, core]
  Help:
    description: Gets the soup cores help for normal players.
    usage: /<command>
  ToggleDrops:
    description: Toggle off or on item drops.
    usage: /<command>
    aliases: tdp
  Spawn:
    description: Teleport a player to spawn.
    usage: /<command>
